// Comprehensive list of subjects for tutoring platform

export const SUBJECT_CATEGORIES = {
  'Mathematics': [
    'Algebra I',
    'Algebra II',
    'Geometry',
    'Trigonometry',
    'Pre-Calculus',
    'Calculus I (AB)',
    'Calculus II (BC)',
    'Calculus III (Multivariable)',
    'Linear Algebra',
    'Differential Equations',
    'Statistics',
    'Probability',
    'Discrete Mathematics',
    'Number Theory',
  ],
  'Science': [
    'General Biology',
    'AP Biology',
    'Anatomy & Physiology',
    'Microbiology',
    'Genetics',
    'Ecology',
    'General Chemistry',
    'AP Chemistry',
    'Organic Chemistry',
    'Biochemistry',
    'General Physics',
    'AP Physics 1',
    'AP Physics 2',
    'AP Physics C (Mechanics)',
    'AP Physics C (E&M)',
    'Earth Science',
    'Environmental Science',
    'Astronomy',
  ],
  'Computer Science': [
    'Introduction to Programming',
    'Python',
    'Java',
    'JavaScript',
    'C++',
    'Data Structures',
    'Algorithms',
    'Web Development',
    'Mobile App Development',
    'Database Systems',
    'Computer Networks',
    'Operating Systems',
    'Software Engineering',
    'Machine Learning',
    'Artificial Intelligence',
    'Cybersecurity',
  ],
  'English & Language Arts': [
    'English Literature',
    'AP English Language',
    'AP English Literature',
    'Creative Writing',
    'Technical Writing',
    'Essay Writing',
    'Grammar & Composition',
    'Reading Comprehension',
    'SAT/ACT English',
    'Public Speaking',
    'Debate',
  ],
  'Social Studies': [
    'World History',
    'AP World History',
    'US History',
    'AP US History',
    'European History',
    'AP European History',
    'Government & Politics',
    'AP US Government',
    'AP Comparative Government',
    'Economics',
    'AP Microeconomics',
    'AP Macroeconomics',
    'Psychology',
    'AP Psychology',
    'Sociology',
    'Geography',
    'Anthropology',
  ],
  'Foreign Languages': [
    'Spanish I',
    'Spanish II',
    'Spanish III',
    'AP Spanish',
    'French I',
    'French II',
    'French III',
    'AP French',
    'German',
    'Italian',
    'Mandarin Chinese',
    'Japanese',
    'Korean',
    'Arabic',
    'Latin',
    'Portuguese',
  ],
  'Business & Finance': [
    'Accounting',
    'Business Management',
    'Marketing',
    'Finance',
    'Entrepreneurship',
    'Business Law',
    'International Business',
  ],
  'Arts & Music': [
    'Music Theory',
    'Piano',
    'Guitar',
    'Violin',
    'Singing/Voice',
    'Art History',
    'Drawing',
    'Painting',
    'Photography',
    'Digital Art',
    'Graphic Design',
  ],
  'Test Preparation': [
    'SAT Prep',
    'ACT Prep',
    'GRE Prep',
    'GMAT Prep',
    'MCAT Prep',
    'LSAT Prep',
    'AP Exam Prep',
    'IB Exam Prep',
  ],
  'Other': [
    'Study Skills',
    'Time Management',
    'College Applications',
    'Personal Finance',
    'Health & Wellness',
  ]
};

// Flattened list for simpler use cases
export const ALL_SUBJECTS = Object.values(SUBJECT_CATEGORIES).flat();

// Popular subjects for quick access
export const POPULAR_SUBJECTS = [
  'Algebra I',
  'Algebra II',
  'Calculus I (AB)',
  'AP Biology',
  'AP Chemistry',
  'General Physics',
  'Python',
  'Data Structures',
  'AP English Literature',
  'US History',
  'AP US History',
  'Spanish I',
  'Spanish II',
  'SAT Prep',
  'ACT Prep',
];
